### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by pocohiter** [j-hc/cmpr#1]
How do I fix this error, sir?

![2022-09-17_17h24_50](https://user-images.githubusercontent.com/101243568/190852299-94872987-391e-4114-83ce-ede643a336cf.png)

**Comment by pocohiter** [comment]
@j-hc How do I fix this error, sir?

![2022-09-17_17h24_50](https://user-images.githubusercontent.com/101243568/190852299-94872987-391e-4114-83ce-ede643a336cf.png)

**Comment by j-hc** [comment]
ffs stop rebranding my repos. im blocking all your accounts.
